[FileDialog]
history=file:///home/cloudygirl, file:///run/media/cloudygirl/OS/Users/Starsjoy/OneDrive/Desktop/电子书教材, file:///run, file:///run/media/cloudygirl/OS/Users/Starsjoy/OneDrive/Desktop/电子书教材/考研资料/王道课本, file:///run/media/cloudygirl/OS/Users/Starsjoy/OneDrive/Desktop/大二下期末
lastVisited=file:///run/media/cloudygirl/OS/Users/Starsjoy/OneDrive/Desktop/大二下期末
qtVersion=6.11.0
shortcuts=file:, file:///home/cloudygirl
sidebarWidth=83
treeViewHeader="@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\x1\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1\xd1\0\0\0\x4\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x4\0\0\0\xf5\0\0\0\x1\0\0\0\0\0\0\0\x39\0\0\0\x1\0\0\0\0\0\0\0=\0\0\0\x1\0\0\0\0\0\0\0\x66\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1)"
viewMode=Detail
